=== Morabotti/travel-app/src/main/resources/dataset.dtd
<!ELEMENT dataset (
        customers*,
        travels*,
        orders*
        )>

<!ELEMENT customers EMPTY>
<!ATTLIST customers
        id CDATA #REQUIRED
        first_name CDATA #REQUIRED
        last_name CDATA #REQUIRED
        email CDATA #REQUIRED
        age CDATA #REQUIRED
        created CDATA #REQUIRED>

<!ELEMENT travels EMPTY>
<!ATTLIST travels
        id CDATA #REQUIRED
        travel_code CDATA #REQUIRED
        name CDATA #REQUIRED
        description CDATA #REQUIRED
        starting_city CDATA #REQUIRED
        destination_city CDATA #REQUIRED
        guided_tour CDATA #REQUIRED
        cost CDATA #REQUIRED
        guide CDATA #IMPLIED
        travel_type CDATA #REQUIRED>

<!ELEMENT orders EMPTY>
<!ATTLIST orders
        id CDATA #REQUIRED
        customer_id CDATA #REQUIRED
        travel_id CDATA #REQUIRED
        start_date CDATA #REQUIRED
        end_date CDATA #REQUIRED
        active CDATA #IMPLIED>

=== Morabotti/travel-app/src/main/resources/dataset.xml
<!DOCTYPE dataset SYSTEM "dataset.dtd">
<dataset>
    <customers first_name="Jesse" last_name="Batman" email="jesse.batman@outlook.com" age="21" created="2018-01-01 00:00:01"/>
    <customers first_name="Esa" last_name="Esimerkki" email="esa.esimerkki@outlook.com" age="23" created="2018-06-01 00:00:10"/>
    <customers first_name="Pekka" last_name="Pylv채s" email="pekka.pylvas@outlook.com" age="24" created="2018-06-01 00:00:10"/>

    <travels
            travel_code="kulttuurirooma19"
            name="Antiikkimatka Roomaan"
            description="Sis채lt채채 opastetun kierroksen Forum Romanumille."
            starting_city="Helsinki"
            destination_city="Rooma"
            guided_tour="1"
            cost="400.50"
            travel_type="culture"
    />
    <travels
            travel_code="pohjoinenvalo2020"
            name="Laskettelumatka lappiin"
            description="Koko perhe laskettelemaan lappiin halvalla."
            starting_city="Helsinki"
            destination_city="Rovaniemi"
            guided_tour="0"
            cost="200.00"
            guide="Pekka Ohjaaja"
            travel_type="sport"
    />

    <orders customer_id="1" travel_id="2" start_date="2019-10-05 00:00:10" end_date="2019-10-08 00:00:10" active="true" />
    <orders customer_id="1" travel_id="1" start_date="2019-10-07 00:00:11" end_date="2019-10-11 00:00:10" active="true" />
    <orders customer_id="2" travel_id="1" start_date="2019-10-09 00:00:12" end_date="2019-10-12 00:00:10" active="false" />
</dataset>
